// System-Aufrufe nachfolgend
pub mod sys_getlastkey;
pub mod sys_gettid;
pub mod sys_hello_world;
pub mod sys_hello_world_print;
pub mod sys_read;
pub mod sys_write;
pub mod sys_get_systime;
pub mod sys_graphical_print;
pub mod sys_graphical_print_pos;
pub mod sys_get_screen_width;
pub mod sys_getpid;
pub mod sys_read_process_name;
pub mod sys_dump_vmas;
pub mod sys_mmap_heap_space;
