######################################
# Environment variables
######################################

[env.development]
CARGO_CFG_TARGET_FAMILY = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/hhu_tosr_os.json"
BUILD_DIRECTORY = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/hhu_tosr_os/debug"
CARGO_BUILD_OPTION = "--lib"

[env.production]
CARGO_CFG_TARGET_FAMILY = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/hhu_tosr_os.json"
BUILD_DIRECTORY = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/hhu_tosr_os/release"
CARGO_BUILD_OPTION = "--release"

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
RUST_TARGET_PATH = "${CARGO_MAKE_WORKING_DIRECTORY}"
SOURCE_DIRECTORY = "${CARGO_MAKE_WORKING_DIRECTORY}/src"
LINKER_FILE = "${CARGO_MAKE_WORKING_DIRECTORY}/linker.x86_64-elf-ld"
RUST_OBJECT = "${BUILD_DIRECTORY}/lib${CARGO_MAKE_PROJECT_NAME}.a"
KERNEL = "${BOOTLOADER_DIRECTORY}/isofiles/boot/${KERNEL_IMAGE}"


######################################
# Build tasks
######################################

# default task
[tasks.default]
alias = "link"

# 
# Compiling Rust sources
#
[tasks.compile]
command = "cargo"
args = [
    "build",
    "-Z",
    "build-std=core,alloc",
    "-Z",
    "build-std-features=compiler-builtins-mem",
    "--target",
    "${CARGO_CFG_TARGET_FAMILY}",
    "${CARGO_BUILD_OPTION}",
]
condition = { files_modified = { input = [
    # The kernel shall be recompiled of any of the input (source) files is newer than the output file
    "${CARGO_MAKE_WORKING_DIRECTORY}/Cargo.toml",
    "${SOURCE_DIRECTORY}/**/*.rs",
], output = [
    # Compiled output file
    "${BUILD_DIRECTORY}/lib${CARGO_MAKE_PROJECT_NAME}*",
] } }

# 
# Compiling ASM sources
#
[tasks.build-boot-asm]
command = "nasm"
args = [
    "-f",
    "elf64",
    "-w+error=label-redef-late",
    "-o",
    "${BUILD_DIRECTORY}/boot.o",
    "${SOURCE_DIRECTORY}/boot/boot.asm",
]
condition = { files_modified = { input = [
    # Source input file
    "${SOURCE_DIRECTORY}/boot/boot.asm",
], output = [
    # Assembled output file
    "${BUILD_DIRECTORY}/boot.o",
] } }

[tasks.build-interrupt-asm]
command = "nasm"
args = [
    "-f",
    "elf64",
    "-w+error=label-redef-late",
    "-o",
    "${BUILD_DIRECTORY}/interrupts.o",
    "${SOURCE_DIRECTORY}/kernel/interrupts/interrupts.asm",
]
condition = { files_modified = { input = [
    # Source input file
    "${SOURCE_DIRECTORY}/kernel/interrupts/interrupts.asm",
], output = [
    # Assembled output file
    "${BUILD_DIRECTORY}/interrupts.o",
] } }

[tasks.build-thread-asm]
command = "nasm"
args = [
    "-f",
    "elf64",
    "-w+error=label-redef-late",
    "-o",
    "${BUILD_DIRECTORY}/thread.o",
    "${SOURCE_DIRECTORY}/kernel/threads/thread.asm",
]
condition = { files_modified = { input = [
    # Source input file
    "${SOURCE_DIRECTORY}/kernel/threads/thread.asm",
], output = [
    # Assembled output file
    "${BUILD_DIRECTORY}/thread.o",
] } }

[tasks.build-syscalls-asm]
command = "nasm"
args = [
    "-f",
    "elf64",
    "-w+error=label-redef-late",
    "-o",
    "${BUILD_DIRECTORY}/syscalls.o",
    "${SOURCE_DIRECTORY}/kernel/syscall/syscalls.asm",
]
condition = { files_modified = { input = [
    # Source input file
    "${SOURCE_DIRECTORY}/kernel/syscall/syscalls.asm",
], output = [
    # Assembled output file
    "${BUILD_DIRECTORY}/syscalls.o",
] } }

# 
# Linking 
#
[tasks.link]
command = "${LINKER}"
args = [
    "-n",
    "-T",
    "${LINKER_FILE}",
    "-o",
    "${KERNEL}",
    "${BUILD_DIRECTORY}/boot.o",
    "${BUILD_DIRECTORY}/interrupts.o",
    "${BUILD_DIRECTORY}/thread.o",
    "${BUILD_DIRECTORY}/syscalls.o",
    "${RUST_OBJECT}",
]
dependencies = [
    "compile",
    "build-boot-asm",
    "build-interrupt-asm",
    "build-thread-asm",
    "build-syscalls-asm",
]
condition = { files_modified = { input = [
    # The input files of tasks.link are the output file of tasks.compile and all asm build tasks
    "${BUILD_DIRECTORY}/lib${CARGO_MAKE_PROJECT_NAME}*",
    "${BUILD_DIRECTORY}/boot.o",
    "${BUILD_DIRECTORY}/interrupts.o",
    "${BUILD_DIRECTORY}/thread.o",
    "${BUILD_DIRECTORY}/syscalls.o",
], output = [
    # The output file is the linked application
    "${KERNEL}",
] } }


######################################
# Cleanup tasks
######################################

[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = ["remove-kernel"]

[tasks.remove-kernel]
command = "rm"
args = ["-f", "${KERNEL}"]
